function y = priorshapederiv(x,parHYPshape,parHYPscale, ...
				 parshape,parscale)
  y = sum(sum( gamExpLogx(parHYPshape,parHYPscale) ...
	       - psi(x) ...
	       + gamExpLogx(parshape,parscale) ));
end
